In [1]:
!pip list

Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 2.0.3
anaconda-project                   0.9.1
anyio                              2.2.0
appdirs                            1.4.4
applaunchservices                  0.2.1
appnope                            0.1.2
appscript                          1.1.2
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.5
astropy                            4.2.1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.6
Babel                              2.9.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0

In [5]:
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 21.4 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [11]:
print(np.version.version)

1.23.4


In [13]:
a = np.random.random_sample((2,3,5))
a

array([[[0.80968616, 0.40354388, 0.38699332, 0.8641008 , 0.84659822],
        [0.78943412, 0.23697286, 0.38555752, 0.9160849 , 0.05877663],
        [0.75381989, 0.6423662 , 0.85538397, 0.88284076, 0.12246927]],

       [[0.75082194, 0.61436632, 0.54334338, 0.88754618, 0.93117679],
        [0.50634088, 0.10992661, 0.74551011, 0.88376075, 0.69636935],
        [0.62526857, 0.80747655, 0.1516226 , 0.47520883, 0.27873455]]])

In [27]:
a1 = np.random.randint(0,20, (2,3,5))
a1

array([[[19,  0, 19,  6, 13],
        [19, 12, 18,  8,  6],
        [ 9,  5,  3, 11, 18]],

       [[ 7,  8,  4, 14,  2],
        [14,  2, 15,  7,  2],
        [12,  3,  3, 12,  4]]])

In [28]:
a2 = np.random.rand(2,3,5)
a2

array([[[0.57106466, 0.98703796, 0.9900262 , 0.47673334, 0.28164191],
        [0.91881236, 0.50741951, 0.63271566, 0.28317841, 0.54247349],
        [0.06837758, 0.75685184, 0.0733617 , 0.08394068, 0.86558617]],

       [[0.29151913, 0.59101967, 0.29482673, 0.86516766, 0.25424589],
        [0.32160818, 0.70448106, 0.00639039, 0.24378985, 0.29041352],
        [0.43792312, 0.14294929, 0.04136863, 0.3888037 , 0.09868148]]])

In [29]:
a

array([[[0.80968616, 0.40354388, 0.38699332, 0.8641008 , 0.84659822],
        [0.78943412, 0.23697286, 0.38555752, 0.9160849 , 0.05877663],
        [0.75381989, 0.6423662 , 0.85538397, 0.88284076, 0.12246927]],

       [[0.75082194, 0.61436632, 0.54334338, 0.88754618, 0.93117679],
        [0.50634088, 0.10992661, 0.74551011, 0.88376075, 0.69636935],
        [0.62526857, 0.80747655, 0.1516226 , 0.47520883, 0.27873455]]])

In [96]:
b = np.ones((5,2,3), dtype = int)

In [97]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [79]:
    if a.shape == b.shape:
        print("Array 'a' y 'b' tienen la misma forma")
    else:
        print("Array 'a' y 'b' no tienen la misma forma")

Array 'a' y 'b' no tienen la misma forma


In [80]:
suma = np.add(a, b)
suma

#no se puede sumar dado que no tienen la misma forma, resulta inconpatible operar entre ellas.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [110]:
c = np.transpose(b, (2,3,5))
c

AxisError: axis 3 is out of bounds for array of dimension 3