In [2]:
#1

import numpy as np
#2

print(np.version.version)

1.23.4


In [3]:
#3
#4

a = np.random.randint(1,50, (2,3,5))
a

array([[[48, 45, 13, 25, 47],
        [ 9, 47, 23, 26, 27],
        [32, 16,  6, 38, 46]],

       [[22, 45, 26, 39, 23],
        [33,  6, 45, 47, 37],
        [ 2, 20, 30,  7, 13]]])

In [18]:
#5
#6

b = np.ones((5,2,3), dtype= int)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [19]:
#7

if a.size == b.size:
    print(f"True the size of a is {a.size} and for b is {b.size}")

True the size of a is 30 and for b is 30


In [20]:
#8 No se pueden juntar porque tienen diferentes configuraciones de lineas y columnas

np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [24]:
#9 

c = np.transpose(b,(1,2,0))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [26]:
#10, ahora funciona porque tienen la misma disposición de filas y columnas

d = np.add(a,c)
d

array([[[49, 46, 14, 26, 48],
        [10, 48, 24, 27, 28],
        [33, 17,  7, 39, 47]],

       [[23, 46, 27, 40, 24],
        [34,  7, 46, 48, 38],
        [ 3, 21, 31,  8, 14]]])

In [30]:
#11 La diferencia es que la a es la original y la d se le ha sumado los valores de la b, que son todo 1, por lo tanto la diferencia
# está en que d es a +1

print(a), print(d)

[[[48 45 13 25 47]
  [ 9 47 23 26 27]
  [32 16  6 38 46]]

 [[22 45 26 39 23]
  [33  6 45 47 37]
  [ 2 20 30  7 13]]]
[[[49 46 14 26 48]
  [10 48 24 27 28]
  [33 17  7 39 47]]

 [[23 46 27 40 24]
  [34  7 46 48 38]
  [ 3 21 31  8 14]]]


(None, None)

In [32]:
#12
#13 El resultado es el mismo ya que al multiplicar cualquier valor por 1, el resultado es el mismo, por lo tanto a = c

e = np.multiply(a,c)
e

array([[[48, 45, 13, 25, 47],
        [ 9, 47, 23, 26, 27],
        [32, 16,  6, 38, 46]],

       [[22, 45, 26, 39, 23],
        [33,  6, 45, 47, 37],
        [ 2, 20, 30,  7, 13]]])

In [38]:
#14

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
d_max, d_min, d_mean

(49, 3, 29.1)

In [40]:
#15

f = np.empty((2,3,5), dtype = int)
f

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [60]:
#16 
#if it's larger than d_min but smaller than d_mean, assign 25 
for i in d[0]:
    for z in d[1]:
        if z > d_min and i < d_mean:
            f = 25

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()